### ISSUE TITLE
Close Card and Re-Opening Behavior

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-editor#40]
### Current Behavior
Today, when we close a card, the following is done:
- The data is removed from our memory
- The card is removed (along with the editor) from the workspace

_This means that any changes the user had made will be lost, unless they had saved prior to closing._

Then when a card is re-opened, the latest data from user branch (if any; if not then master) is retrieved and given to the editor and card is placed (back?) into the workspace.

### Observations
1. should we warn before closing the card with changed data?
2. how would we know it had been changed?
3. the editor is not aware that all this is going on... when a new editor is instantiated on re-opening, what is it doing? It may have trouble with trying to deal with data it thinks it already has.

### Proposals
1. Instead of removing the card when closed, make it invisible (or use the minimize feature in gE). And toggle if re-opened to make re-appear. This way the card and the editor are never disassociated. And this might solve issue unfoldingWord/uw-editor#44 
2. Show a warning message that data is not saved and let them choose to save or "close"

@abelpz @larsgson @superdav42

**Comment by abelpz** [comment]
@mandolyte Proposal 2 is the most common way to deal with it, and probably the most easy to implement provided that we have a way to know there has been changes, which we probably have by knowing the history stack length from epitelete.

**Comment by abelpz** [comment]
Yes, I also believe the editor doesn't expose that information. We should
add an issue to include this.

**Comment by abelpz** [comment]
There is a way of doing it from the app by accessing the cache from Lars's pk-cache, but maybe it would be better to have that come from the editor itself. So we would add a callback onClose or something like that, that should have an event argument with this needed info.

**Comment by mandolyte** [comment]
I think an onClose is too late. I think an isChanged fired on the first
change might work better. Then the app will already know when the tries to
close the card that it should provide a warning.

**Comment by larsgson** [comment]
It seems fairly easy to provide such an isChanged event. 
I can work on this to see if this then can be used to have this fixed.

**Comment by larsgson** [comment]
My first attempt does not work well enough - the editor only notices a change when the cursor is moved outside a certain block (the very block being edited). 

The result is that currently somebody might have done a lot of changes in the first block and when the close button is closed, then these changes are not noticed - and no warning will be sent.

I am now diving deep into the HtmlEditor component and will try to catch an onChange event in there, so that this event can be made visible also on the outside.

**Comment by mandolyte** [comment]
@larsgson could this work at onBlur?

- let the app provide a function for the editor to execute that takes a Boolean... let's call it "setIsDirty(Boolean)"
- check the history stack: if zero, then execute "setIsDirty(false)", otherwise "setIsDirty(true)
- the function provided by the app would be a set state function:
```js
const [isDirty, setIsDirty] = useState(false)
```
- then the app's close card handler could check the value of "isDirty"
- if false, then proceed to close the card
- if true, then open a dialog warning that data has not been saved and offer two choices:
  - a button to save the data
  - a button to discard the data

thoughts?

**Comment by larsgson** [comment]
@mandolyte 
Yes, something like that is also what I was aiming for in my first attempt, but my aim would be to be able to set the isDirty state even before onBlur. 

I now think I basically have this all working as a small added event to HtmlEditor. Unfortunately I am now running into problems with updating HtmlEditor in the xelah repository, since it is a monorepo. I am not familiar with how to get updates to work in here.

Once I get this update done in the monorepo, then I think auch an isDirty state should become intuitive to use.
